import { invoke,isTauri } from '@tauri-apps/api/core';
import { useEffect, useMemo, useRef, useState } from 'react';
import { editPages, type DocumentSnapshot, type PageEdit } from '../bridge';
import type { Locale } from '../i18n';
import './pages-panel.css';
export const pagesLabels={
 ja:{title:'ページ',single:'単ページ',facing:'見開き',binding:'綴じ方向',ltr:'左開き（左綴じ）',rtl:'右開き（右綴じ）',add:'ページを追加',duplicate:'ページを複製',remove:'ページを削除',before:'前へ移動',after:'後へ移動',page:'ページ',count:'ページ',hint:'クリックでページを開く。ドラッグで順序を変更。見開きの編集対象は青枠のページです。',layout:'ページ構成',first:'先頭ページは単独で配置されます。'},
 en:{title:'Pages',single:'Single pages',facing:'Facing pages',binding:'Binding',ltr:'Left binding (left to right)',rtl:'Right binding (right to left)',add:'Add page',duplicate:'Duplicate page',remove:'Delete page',before:'Move earlier',after:'Move later',page:'Page',count:'pages',hint:'Click to open a page. Drag to reorder. The blue page is the active editing target.',layout:'Page layout',first:'The first page is placed on its own.'},
 'zh-CN':{title:'页面',single:'单页',facing:'对页',binding:'装订方向',ltr:'左装订（从左到右）',rtl:'右装订（从右到左）',add:'添加页面',duplicate:'复制页面',remove:'删除页面',before:'向前移动',after:'向后移动',page:'页面',count:'页',hint:'单击打开页面，拖动调整顺序。蓝色页面为当前编辑目标。',layout:'页面布局',first:'首页单独排列。'},
};
export function PagesPanel({locale,document,enabled,onUpdate}:{locale:Locale;document:DocumentSnapshot;enabled:boolean;onUpdate:(d:DocumentSnapshot)=>void}){
 const t=pagesLabels[locale],book=document.pages;
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[drag,setDrag]=useState<number|null>(null),[drop,setDrop]=useState<number|null>(null);
 const [images,setImages]=useState<Record<string,string>>({}),[visible,setVisible]=useState<string[]>([]);
 const listRef=useRef<HTMLDivElement>(null), inFlight=useRef(false), refresh=useRef<()=>void>(()=>{});
 useEffect(()=>{const root=listRef.current;if(!root)return;const shown=new Set<string>();const observer=new IntersectionObserver(entries=>{for(const entry of entries){const id=(entry.target as HTMLElement).dataset.pageId!;if(entry.isIntersecting)shown.add(id);else shown.delete(id);}setVisible(Array.from(shown));},{root,rootMargin:'80px'});root.querySelectorAll('[data-page-id]').forEach(n=>observer.observe(n));return()=>observer.disconnect();},[book.pages.length,book.facing,book.binding]);
 const visibleKey=visible.slice().sort().join('|');
 useEffect(()=>{let live=true;if(!isTauri())return;const run=async()=>{if(!live||inFlight.current||!enabled)return;const ids=new Set(visibleKey.split('|'));const indices=book.pages.map((p,i)=>ids.has(p.id)?i:-1).filter(i=>i>=0).slice(0,64);if(!indices.length)return;inFlight.current=true;try{const result=await invoke<[string,string][]>('page_thumbnails',{indices});if(live)setImages(old=>({...old,...Object.fromEntries(result)}));}catch{/* The page icon remains usable if a thumbnail cannot be generated. */}finally{inFlight.current=false;if(!live)refresh.current();}};refresh.current=()=>{void run();};const timer=window.setTimeout(refresh.current,300);return()=>{live=false;clearTimeout(timer);};},[document.revision,visibleKey,enabled]);
 const spreads=useMemo(()=>{const groups=new Map<number,typeof book.pages>();for(const page of book.pages){const row=groups.get(page.spread)??[];row.push(page);groups.set(page.spread,row);}return Array.from(groups.values()).map(row=>row.sort((a,b)=>a.side==='left'?-1:b.side==='left'?1:a.number-b.number));},[book]);
 async function run(edit:PageEdit){if(busy||!enabled)return;setBusy(true);setError('');try{onUpdate(await editPages(edit));}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div className="pages-panel"><h3>{t.title}<small>{book.pages.length} {t.count}</small></h3><fieldset disabled={!enabled||busy}><label>{t.layout}<select aria-label={t.layout} value={book.facing?'facing':'single'} onChange={e=>void run({action:'layout',facing:e.target.value==='facing'})}><option value="single">{t.single}</option><option value="facing">{t.facing}</option></select></label><label>{t.binding}<select aria-label={t.binding} value={book.binding} onChange={e=>void run({action:'layout',binding:e.target.value as typeof book.binding})}><option value="leftToRight">{t.ltr}</option><option value="rightToLeft">{t.rtl}</option></select></label></fieldset>
 <div ref={listRef} className={`page-spreads${book.facing?' facing':''}`} role="list" aria-label={t.title}>{spreads.map(row=><div className="page-spread" key={row.map(p=>p.id).join('-')} role="listitem">{row.length===1&&book.facing&&row[0].side==='right'&&<span className="page-blank"/>}{row.map(page=>{const index=page.number-1;return <button key={page.id} data-page-id={page.id} type="button" disabled={!enabled||busy} draggable={enabled&&!busy} aria-label={`${t.page} ${page.number}`} aria-pressed={book.active===index} className={`page-tile ${page.side}${drop===index?' drop-target':''}`} onClick={()=>void run({action:'select',index})} onDragStart={e=>{setDrag(index);e.dataTransfer.setData('application/x-lumapaint-page',String(index));e.dataTransfer.effectAllowed='move';}} onDragOver={e=>{if(drag!==null){e.preventDefault();setDrop(index);}}} onDragLeave={()=>setDrop(null)} onDragEnd={()=>{setDrag(null);setDrop(null);}} onDrop={e=>{e.preventDefault();setDrop(null);const from=drag;setDrag(null);if(from===null||from===index)return;void(async()=>{if(busy)return;setBusy(true);setError('');try{await editPages({action:'select',index:from});onUpdate(await editPages({action:from<index?'moveAfter':'moveBefore',index}));}catch(e){setError(String(e));}finally{setBusy(false);}})();}}><span className="page-paper" style={{aspectRatio:`${page.width}/${page.height}`}}>{images[page.id]?<img src={images[page.id]} alt=""/>:<i/>}</span><span>{page.number}</span></button>;})}{row.length===1&&book.facing&&row[0].side==='left'&&<span className="page-blank"/>}<small className="spread-number">{row.map(p=>p.number).sort((a,b)=>a-b).join('–')}</small></div>)}</div>
 <div className="page-actions"><button disabled={!enabled||busy||book.pages.length>=512} onClick={()=>void run({action:'add'})} title={t.add}>＋ {t.add}</button><button disabled={!enabled||busy||book.pages.length>=512} onClick={()=>void run({action:'duplicate'})}>{t.duplicate}</button><button disabled={!enabled||busy||book.pages.length===1} onClick={()=>void run({action:'delete'})}>{t.remove}</button><button disabled={!enabled||busy||book.active===0} onClick={()=>void run({action:'moveBefore',index:book.active-1})} title={t.before}>↑</button><button disabled={!enabled||busy||book.active===book.pages.length-1} onClick={()=>void run({action:'moveAfter',index:book.active+1})} title={t.after}>↓</button></div>
 <p className="pages-hint">{t.hint}{book.facing&&<> {t.first}</>}</p>{error&&<p role="alert">{error}</p>}</div>;
}
