import {listen} from '@tauri-apps/api/event';
import {invoke,isTauri} from '@tauri-apps/api/core';
import {useEffect,useRef,useState} from 'react';
import {getCurrentWebviewWindow} from '@tauri-apps/api/webviewWindow';
import type {Locale} from '../i18n';
import type {LayerSnapshot} from '../bridge';
import {cloneStampLabels} from './CloneStampControls';
export const paintBucketLabels={ja:{sample:'参照先',currentLayer:'現在のレイヤー',referenceLayers:'指定レイヤー',excludeText:'編集可能な文字を除外',referencesHint:'表示中のレイヤーを最大64件選択します。チェックを外したレイヤーは参照しません。',missingReferences:'削除済みの参照があります。選択し直してください。',clear:'参照を解除',closeGap:'隙間閉じ (px)',areaOffset:'領域拡張・縮小 (px)',gapHint:'隣接を有効にすると、指定半径で狭い隙間を閉じます。細い領域は省略される場合があります。',source:'塗りつぶし',foreground:'描画色',pattern:'パターン',patterns:['市松模様','斜線','ドット'],patternSize:'パターン幅',tolerance:'許容値',antiAlias:'アンチエイリアス',contiguous:'隣接',allLayers:'すべてのレイヤー',hint:'領域をクリックして塗りつぶし · Shift+G：塗りつぶし'},en:{sample:'Sample',currentLayer:'Current layer',referenceLayers:'Selected references',excludeText:'Exclude editable text',referencesHint:'Choose up to 64 visible layers. Unchecked layers are not sampled.',missingReferences:'A reference was deleted. Choose references again.',clear:'Clear references',closeGap:'Close gap (px)',areaOffset:'Grow / shrink (px)',gapHint:'With Contiguous enabled, the radius closes narrow gaps. Thin regions may be omitted.',source:'Fill',foreground:'Foreground',pattern:'Pattern',patterns:['Checker','Stripes','Dots'],patternSize:'Pattern size',tolerance:'Tolerance',antiAlias:'Anti-alias',contiguous:'Contiguous',allLayers:'All layers',hint:'Click an area to fill · Shift+G: Paint Bucket'},'zh-CN':{sample:'参考来源',currentLayer:'当前图层',referenceLayers:'指定图层',excludeText:'排除可编辑文字',referencesHint:'最多选择64个可见图层。未勾选的图层不会被采样。',missingReferences:'参考图层已删除，请重新选择。',clear:'清除参考',closeGap:'闭合间隙 (px)',areaOffset:'扩展／收缩 (px)',gapHint:'启用连续时，以指定半径闭合狭窄间隙。细小区域可能被忽略。',source:'填充',foreground:'前景色',pattern:'图案',patterns:['棋盘','斜线','圆点'],patternSize:'图案大小',tolerance:'容差',antiAlias:'消除锯齿',contiguous:'连续',allLayers:'所有图层',hint:'单击区域填充 · Shift+G：油漆桶'}};
export const defaultPaintBucketSettings={source:'foreground',pattern:'checker',patternSize:8,mode:'normal',opacity:1,tolerance:32,antiAlias:true,contiguous:true,allLayers:false,useReferenceLayers:false,referenceLayers:[] as string[],excludeText:false,closeGap:0,areaOffset:0};
type Settings=typeof defaultPaintBucketSettings;
export function PaintBucketControls({locale,details=false,layers=[],onError,onChange}:{locale:Locale;details?:boolean;layers?:LayerSnapshot[];onError?:(error:string)=>void;onChange?:(settings:Settings)=>void}){
 const t=paintBucketLabels[locale],common=cloneStampLabels[locale];const [settings,setSettings]=useState(defaultPaintBucketSettings);
 const edited=useRef(false);
 useEffect(()=>{
  let live=true;
  const refresh=()=>{if(isTauri())void invoke<Settings>('paint_bucket_settings').then(value=>{if(live&&(!onChange||!edited.current)){setSettings(value);onChange?.(value);}}).catch(error=>onError?.(String(error)));};
  refresh();
  const listeners=isTauri()?[listen('paint-bucket-settings-changed',refresh),...(!onChange?[getCurrentWebviewWindow().listen('documents-changed',refresh)]:[])]:[];
  return()=>{live=false;listeners.forEach(listener=>void listener.then(unlisten=>unlisten()).catch(()=>{}));};
 },[]);
 const update=(patch:Partial<Settings>)=>{const next={...settings,...patch};edited.current=true;setSettings(next);if(onChange)onChange(next);else if(isTauri())void invoke('set_paint_bucket_settings',{settings:next}).catch(error=>onError?.(String(error)));};
 const number=(label:string,key:'opacity'|'tolerance'|'patternSize'|'closeGap'|'areaOffset',min:number,max:number,scale=1)=><label><span>{label}</span><span className="clone-stamp-value"><input type="number" disabled={key==='closeGap'&&!settings.contiguous} title={key==='closeGap'?t.gapHint:undefined} aria-label={label} min={min} max={max} value={Math.round(settings[key]*scale)} onChange={e=>{const value=e.currentTarget.valueAsNumber;if(Number.isInteger(value)&&value>=min&&value<=max)update({[key]:value/scale});}}/>{scale===100?'%':''}</span></label>;
 return <div title={t.hint} className={`paint-bucket-controls clone-stamp-controls ${details?'clone-stamp-details':''}`}>
 <label>{t.source}<select value={settings.source} onChange={e=>update({source:e.target.value})}><option value="foreground">{t.foreground}</option><option value="pattern">{t.pattern}</option></select></label>
 {settings.source==='pattern'&&<><label>{t.pattern}<select value={settings.pattern} onChange={e=>update({pattern:e.target.value})}>{['checker','stripes','dots'].map((v,i)=><option key={v} value={v}>{t.patterns[i]}</option>)}</select></label>{number(t.patternSize,'patternSize',2,512)}</>}
 <label>{common.mode}<select value={settings.mode} onChange={e=>update({mode:e.target.value})}>{['normal','multiply','screen','overlay','darken','lighten'].map((v,i)=><option key={v} value={v}>{common.modes[i]}</option>)}</select></label>
 {number(common.opacity,'opacity',0,100,100)}{number(t.tolerance,'tolerance',0,255)}
 {(['antiAlias','contiguous'] as const).map(key=><label key={key}><input type="checkbox" checked={settings[key]} onChange={e=>update({[key]:e.target.checked})}/>{t[key]}</label>)}
 <label>{t.sample}<select aria-label={t.sample} value={settings.useReferenceLayers?'reference':settings.allLayers?'all':'current'} onChange={e=>update({useReferenceLayers:e.target.value==='reference',allLayers:e.target.value==='all'})}><option value="current">{t.currentLayer}</option><option value="all">{t.allLayers}</option><option value="reference">{t.referenceLayers}</option></select></label>
 {(settings.useReferenceLayers||settings.allLayers)&&<label><input type="checkbox" checked={settings.excludeText} onChange={e=>update({excludeText:e.target.checked})}/>{t.excludeText}</label>}
 {details&&settings.useReferenceLayers&&<fieldset className="paint-bucket-references"><legend>{t.referenceLayers}</legend><div className="paint-bucket-reference-list">{layers.filter(layer=>['paint','vector','svg'].includes(layer.kind)).map(layer=><label key={layer.id} title={layer.name}><input type="checkbox" aria-label={layer.name} checked={settings.referenceLayers.includes(layer.id)} disabled={(!layer.visible&&!settings.referenceLayers.includes(layer.id))||(!settings.referenceLayers.includes(layer.id)&&settings.referenceLayers.length>=64)} onChange={e=>update({referenceLayers:e.target.checked?[...settings.referenceLayers,layer.id]:settings.referenceLayers.filter(id=>id!==layer.id)})}/><span>{layer.name}</span></label>)}</div><p>{t.referencesHint}</p>{settings.referenceLayers.some(id=>!layers.some(layer=>layer.id===id))&&<p role="alert">{t.missingReferences}</p>}<button type="button" onClick={()=>update({referenceLayers:[]})}>{t.clear}</button></fieldset>}
 {details&&<>{number(t.closeGap,'closeGap',0,16)}{number(t.areaOffset,'areaOffset',-32,32)}<p>{t.gapHint}</p><p>{t.hint}</p></>}
 </div>;
}
