import { rulerGuide } from '../bridge';
import { useEffect, useRef, useState } from 'react';
import { getCurrentWebviewWindow } from '@tauri-apps/api/webviewWindow';
import { isTauri } from '@tauri-apps/api/core';
import type { Locale } from '../i18n';
import type { RulerViewport } from '../bridge';
import { measurementUnits, pixelsPerMeasurement, setMeasurementUnit, unitName, unitSymbols, useMeasurementUnit } from '../measurement-units';
import './rulers.css';
import { rulerTicks } from '../ruler-math';
export function Rulers({locale,resolution,viewport:initial}:{locale:Locale;resolution:number;viewport:RulerViewport|null}) {
  const unit=useMeasurementUnit(), [viewport,setViewport]=useState(initial);
  const [menu,setMenu]=useState<{x:number;y:number}|null>(null), [error,setError]=useState('');
  const menuRef=useRef<HTMLDivElement>(null);
  const guideCleanup=useRef<()=>void>(()=>{});
  useEffect(()=>()=>guideCleanup.current(),[]);
  useEffect(()=>setViewport(initial),[initial]);
  useEffect(()=>{ if(!isTauri())return;let live=true,frame=0;let latest:RulerViewport;let unlisten=()=>{};
    void getCurrentWebviewWindow().listen<RulerViewport>('canvas-ruler-changed',e=>{latest=e.payload;if(!frame)frame=requestAnimationFrame(()=>{frame=0;if(live)setViewport(latest);});}).then(fn=>{if(live)unlisten=fn;else fn();});
    return()=>{live=false;unlisten();cancelAnimationFrame(frame);};
  },[]);
  useEffect(()=>{if(!menu)return;menuRef.current?.querySelector<HTMLButtonElement>('[aria-checked="true"]')?.focus();
    const close=(e:PointerEvent)=>{if(!menuRef.current?.contains(e.target as Node))setMenu(null);};
    window.addEventListener('pointerdown',close,true);return()=>window.removeEventListener('pointerdown',close,true);
  },[menu]);
  useEffect(()=>{window.dispatchEvent(new Event('panel-layout-change'));return()=>{window.dispatchEvent(new Event('panel-layout-change'));};},[menu,error]);
  const open=(x:number,y:number)=>{setError('');setMenu({x:Math.min(x,window.innerWidth-210),y:Math.min(y,window.innerHeight-220)});};
  const v=viewport??{width:0,height:0,originX:0,originY:0,zoom:1};
  const factor=pixelsPerMeasurement(unit,resolution)*v.zoom;
  const render=(vertical:boolean)=>{const ticks=rulerTicks(vertical?v.height:v.width,vertical?v.originY:v.originX,factor);return <svg aria-hidden="true" width={vertical?24:'100%'} height={vertical?'100%':24}>{ticks.map((tick,i)=><g key={i}>{vertical?<><path d={`M24 ${tick.position}h-${tick.major?10:5}`}/>{tick.major&&<text transform={`translate(10 ${tick.position+3}) rotate(-90)`}>{tick.label}</text>}</>:<><path d={`M${tick.position} 24v-${tick.major?10:5}`}/>{tick.major&&<text x={tick.position+3} y={11}>{tick.label}</text>}</>}</g>)}</svg>;};
  const dragGuide=(e:React.PointerEvent<HTMLDivElement>,axis:'horizontal'|'vertical')=>{
    if(e.button!==0||!viewport)return;guideCleanup.current();e.preventDefault();setMenu(null);
    const target=e.currentTarget, slot=target.closest('.canvas-stage')?.querySelector('.native-slot');if(!slot)return;
    const rect=slot.getBoundingClientRect();const view=viewport;
    let chain=Promise.resolve(),frame=0,last=e,finished=false;
    const position=(event:React.PointerEvent|PointerEvent)=>axis==='horizontal'?(event.clientY-rect.top-view.originY)/view.zoom:(event.clientX-rect.left-view.originX)/view.zoom;
    const send=(event:React.PointerEvent|PointerEvent,phase:number)=>{const p=position(event);chain=chain.then(()=>rulerGuide(axis,p,phase)).catch(err=>setError(String(err)));};
    send(e,0);target.setPointerCapture(e.pointerId);
    const move=(event:PointerEvent)=>{if(event.pointerId!==e.pointerId)return;last=event as unknown as React.PointerEvent<HTMLDivElement>;if(!frame)frame=requestAnimationFrame(()=>{frame=0;if(!finished)send(last,1);});};
    const end=(event:PointerEvent)=>{if(event.pointerId!==e.pointerId)return;finished=true;cancelAnimationFrame(frame);
      const inside=event.clientX>=rect.left&&event.clientX<=rect.right&&event.clientY>=rect.top&&event.clientY<=rect.bottom;
      send(event,event.type==='pointerup'&&inside?2:3);cleanup();};
    const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){finished=true;cancelAnimationFrame(frame);send(last,3);cleanup();}};
    const cleanup=()=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',end);target.removeEventListener('pointercancel',end);window.removeEventListener('keydown',key,true);guideCleanup.current=()=>{};if(target.hasPointerCapture(e.pointerId))target.releasePointerCapture(e.pointerId);};
    guideCleanup.current=()=>{finished=true;cancelAnimationFrame(frame);send(last,3);cleanup();};
    target.addEventListener('pointermove',move);target.addEventListener('pointerup',end);target.addEventListener('pointercancel',end);window.addEventListener('keydown',key,true);
  };
  const title=locale==='ja'?'定規の単位':locale==='en'?'Ruler units':'标尺单位';
  const events={onContextMenu:(e:React.MouseEvent)=>{e.preventDefault();open(e.clientX,e.clientY);},onKeyDown:(e:React.KeyboardEvent)=>{if(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10')){e.preventDefault();const r=e.currentTarget.getBoundingClientRect();open(r.left+10,r.top+10);}}};
  return <>{error&&!menu&&<div className="ruler-error" role="alert" data-floating-panel>{error}<button aria-label={locale==='ja'?'閉じる':locale==='en'?'Close':'关闭'} onClick={()=>setError('')}>×</button></div>}<button className="ruler-corner" title={title} aria-label={title} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();open(r.left,r.bottom);}} {...events}>{unitSymbols[unit]}</button><div className="ruler-horizontal" onPointerDown={e=>dragGuide(e,'horizontal')} role="button" tabIndex={0} aria-label={title} {...events}>{render(false)}</div><div className="ruler-vertical" onPointerDown={e=>dragGuide(e,'vertical')} role="button" tabIndex={0} aria-label={title} {...events}>{render(true)}</div>{menu&&<div ref={menuRef} className="ruler-menu" data-floating-panel role="menu" aria-label={title} style={{left:menu.x,top:menu.y}} onKeyDown={e=>{if(e.key==='Escape'){setMenu(null);e.stopPropagation();}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const items=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('button'));const index=items.indexOf(document.activeElement as HTMLButtonElement);items[(index+(e.key==='ArrowDown'?1:items.length-1))%items.length]?.focus();}}}>{measurementUnits.map(value=><button key={value} role="menuitemradio" aria-checked={unit===value} onClick={()=>{void setMeasurementUnit(value).then(()=>setMenu(null)).catch(e=>setError(String(e)));}}><span>{unit===value?'✓':''}</span>{unitName(value,locale)}<small>{unitSymbols[value]}</small></button>)}{error&&<p role="alert">{error}</p>}</div>}</>;
}
