import {useEffect,useState} from 'react';import {invoke,isTauri} from '@tauri-apps/api/core';import {listen} from '@tauri-apps/api/event';import type {Locale} from '../i18n';import type {CanvasTool} from '../bridge';
export const pathSelectionTools=['selectionBrush','lasso','polygonLasso','magneticLasso'] as const;
export const isPathSelection=(tool:CanvasTool)=>(pathSelectionTools as readonly string[]).includes(tool);
export const defaultSelectionPathSettings={mode:'replace',diameter:32,magneticWidth:10,magneticContrast:10,magneticFrequency:8,allLayers:true};
export const selectionPathLabels={ja:{mode:'選択モード',modes:['新規','追加','削除'],diameter:'直径 (px)',magneticWidth:'幅 (px)',magneticContrast:'コントラスト (%)',magneticFrequency:'頻度',allLayers:'すべてのレイヤー',confirm:'選択を確定',cancel:'取消',hint:'ドラッグで選択 · Shift：追加 · Option：削除 · Escape：取消',pointHint:'クリックで点を追加 · 始点をクリック／ダブルクリック／Enter：確定 · Delete：直前の点を削除'},en:{mode:'Selection mode',modes:['New','Add','Subtract'],diameter:'Diameter (px)',magneticWidth:'Width (px)',magneticContrast:'Contrast (%)',magneticFrequency:'Frequency',allLayers:'All layers',confirm:'Close selection',cancel:'Cancel',hint:'Drag to select · Shift: add · Option: subtract · Escape: cancel',pointHint:'Click to add points · start point / double-click / Enter: close · Delete: remove last point'},'zh-CN':{mode:'选择模式',modes:['新建','添加','减去'],diameter:'直径 (px)',magneticWidth:'宽度 (px)',magneticContrast:'对比度 (%)',magneticFrequency:'频率',allLayers:'所有图层',confirm:'完成选择',cancel:'取消',hint:'拖动选择 · Shift：添加 · Option：减去 · Escape：取消',pointHint:'单击添加点 · 起点／双击／Enter：完成 · Delete：删除上一点'}};
type Settings=typeof defaultSelectionPathSettings;
export function SelectionPathControls({locale,tool,details=false,onError,onChange}:{locale:Locale;tool:CanvasTool;details?:boolean;onError?:(error:string)=>void;onChange?:(settings:Settings)=>void}){
 const t=selectionPathLabels[locale];const[settings,setSettings]=useState(defaultSelectionPathSettings);
 useEffect(()=>{let live=true;const refresh=()=>{if(isTauri())void invoke<Settings>('selection_tool_settings').then(value=>{if(live){setSettings(value);onChange?.(value);}}).catch(error=>onError?.(String(error)));};refresh();const sub=isTauri()?listen('selection-tool-settings-changed',refresh):null;return()=>{live=false;void sub?.then(fn=>fn());};},[]);
 const update=(patch:Partial<Settings>)=>{const next={...settings,...patch};setSettings(next);if(onChange)onChange(next);else if(isTauri())void invoke('set_selection_tool_settings',{settings:next}).catch(error=>onError?.(String(error)));};
 const numeric=(key:'diameter'|'magneticWidth'|'magneticContrast'|'magneticFrequency',min:number,max:number)=><label><span>{t[key]}</span><input aria-label={t[key]} type="number" min={min} max={max} value={settings[key]} onChange={e=>{const value=e.currentTarget.valueAsNumber;if(Number.isFinite(value)&&value>=min&&value<=max)update({[key]:value});}}/></label>;
 return <div className={`paint-bucket-controls clone-stamp-controls ${details?'clone-stamp-details':''}`}><label>{t.mode}<select value={tool==='selectionBrush'&&settings.mode==='replace'?'add':settings.mode} onChange={e=>update({mode:e.target.value})}>{['replace','add','subtract'].map((v,i)=>tool==='selectionBrush'&&i===0?null:<option key={v} value={v}>{t.modes[i]}</option>)}</select></label>
 {tool==='selectionBrush'&&numeric('diameter',1,512)}{tool==='magneticLasso'&&<>{numeric('magneticWidth',1,40)}{numeric('magneticContrast',0,100)}{numeric('magneticFrequency',1,100)}<label><input type="checkbox" checked={settings.allLayers} onChange={e=>update({allLayers:e.target.checked})}/>{t.allLayers}</label></>}
 {!details&&<><button onClick={()=>void invoke('selection_path_action',{confirm:true}).catch(e=>onError?.(String(e)))}>{t.confirm}</button><button onClick={()=>void invoke('selection_path_action',{confirm:false}).catch(e=>onError?.(String(e)))}>{t.cancel}</button></>}
 {details&&<p>{tool==='lasso'||tool==='selectionBrush'?t.hint:t.pointHint}</p>}</div>;
}
