import {useEffect,useRef,useState} from 'react';
import {invoke,isTauri} from '@tauri-apps/api/core';
import {binding,displayKey,eventKey,validKey,readShortcuts,saveShortcuts,type ShortcutSnapshot} from '../shortcuts';
import {shortcutLabels} from '../shortcut-i18n';
import type {Locale} from '../i18n';
import './shortcut-dialog.css';
export function ShortcutDialog({locale,onClose}:{locale:Locale;onClose:()=>void}){
 const t=shortcutLabels[locale],dialog=useRef<HTMLDialogElement>(null),list=useRef<HTMLDivElement>(null);
 const [draft,setDraft]=useState<ShortcutSnapshot|null>(null),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[area,setArea]=useState(''),[matchCase,setMatchCase]=useState(false),[candidate,setCandidate]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[naming,setNaming]=useState(false),[name,setName]=useState('');
 useEffect(()=>{dialog.current?.showModal();let active=true;void readShortcuts().then(s=>{if(active){setDraft(s);setSelected(s.commands[0]?.id??'');}}).catch(e=>setError(String(e)));return()=>{active=false;};},[]);
 const command=draft?.commands.find(c=>c.id===selected),activeSet=draft?.settings.sets.find(s=>s.id===draft.settings.active);
 const conflicts=candidate&&draft?draft.commands.filter(c=>c.id!==selected&&binding(draft.settings,c)===candidate):[];
 const invalid=candidate&&!validKey(candidate);
 const setKey=(id:string,key:string)=>setDraft(d=>d&&({...d,settings:{...d.settings,sets:d.settings.sets.map(s=>s.id===d.settings.active?{...s,bindings:{...s.bindings,[id]:key}}:s)}}));
 const choose=(id:string)=>{setSelected(id);setCandidate('');setError('');};
 function assign(replace=false){if(!command||invalid||!candidate||conflicts.length&&!replace)return;setDraft(d=>{if(!d)return d;const bindings={...d.settings.sets.find(s=>s.id===d.settings.active)!.bindings};for(const c of conflicts)bindings[c.id]='';bindings[command!.id]=candidate;return{...d,settings:{...d.settings,sets:d.settings.sets.map(s=>s.id===d.settings.active?{...s,bindings}:s)}};});setCandidate('');}
 function duplicate(){if(!draft||!name.trim()||draft.settings.sets.some(s=>s.name.toLowerCase()===name.trim().toLowerCase())){setError(t.duplicate);return;}const id=crypto.randomUUID();setDraft({...draft,settings:{...draft.settings,active:id,sets:[...draft.settings.sets,{id,name:name.trim(),bindings:{...activeSet?.bindings}}]}});setNaming(false);setName('');setError('');}
 async function save(){if(!draft||busy)return;if(candidate){setError(t.assign);return;}setBusy(true);setError('');try{await saveShortcuts(draft.settings);onClose();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function exportText(){if(!draft)return;const text=[`${t.title} — ${activeSet?.name}`,`${t.command}\t${t.shortcut}`,...draft.commands.map(c=>`${c.category} > ${c.label}\t${displayKey(binding(draft.settings,c))||t.unassigned}`)].join('\n');try{if(isTauri())await invoke('export_shortcuts',{text});else{const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='LumaPaint-shortcuts.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(e){setError(String(e));}}
 const normalize=(v:string)=>matchCase?v:v.toLocaleLowerCase(locale);const commands=draft?.commands.filter(c=>(!area||c.category===area)&&normalize(`${c.category} ${c.label} ${displayKey(binding(draft.settings,c))}`).includes(normalize(query)))??[];
 return <dialog ref={dialog} className="shortcut-dialog" aria-labelledby="shortcut-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><form onSubmit={e=>{e.preventDefault();void save();}}>
 <header><h2 id="shortcut-title">{t.title}</h2><p>{t.hint}</p></header>
 <fieldset disabled={busy||!draft} className="shortcut-controls"><div className="shortcut-set"><label>{t.set}<select value={draft?.settings.active??''} onChange={e=>{const active=e.target.value;setDraft(d=>d&&({...d,settings:{...d.settings,active}}));setCandidate('');}}>{draft?.settings.sets.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button type="button" onClick={()=>setNaming(v=>!v)} disabled={(draft?.settings.sets.length??0)>=32}>{t.newSet}</button><button type="button" disabled={(draft?.settings.sets.length??0)<2} onClick={()=>{if(!draft)return;const sets=draft.settings.sets.filter(s=>s.id!==draft.settings.active);setDraft({...draft,settings:{...draft.settings,sets,active:sets[0].id}});setCandidate('');}}>{t.deleteSet}</button></div>
 {naming&&<div className="shortcut-set"><label>{t.name}<input value={name} maxLength={80} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();duplicate();}}} autoFocus/></label><button type="button" onClick={duplicate}>{t.ok}</button></div>}
 <div className="shortcut-filter"><label>{t.area}<select value={area} onChange={e=>setArea(e.target.value)}><option value="">{t.all}</option>{[...new Set(draft?.commands.map(c=>c.category))].map(c=><option key={c}>{c}</option>)}</select></label><label className="shortcut-search"><span>{t.search}</span><input type="search" value={query} placeholder={t.search} onChange={e=>setQuery(e.target.value)}/></label><label className="shortcut-case"><input type="checkbox" checked={matchCase} onChange={e=>setMatchCase(e.target.checked)}/>{t.caseSensitive}</label></div>
 </fieldset>
 <div className="shortcut-columns"><div className="shortcut-table" ref={list} role="listbox" aria-label={t.command} aria-activedescendant={command?`shortcut-${command.id}`:undefined} tabIndex={0} onKeyDown={e=>{if(!['ArrowDown','ArrowUp'].includes(e.key))return;e.preventDefault();const index=commands.findIndex(c=>c.id===selected);const next=commands[Math.max(0,Math.min(commands.length-1,index+(e.key==='ArrowDown'?1:-1)))];if(next){choose(next.id);document.getElementById(`shortcut-${next.id}`)?.scrollIntoView({block:'nearest'});}}}><div className="shortcut-table-head"><span>{t.command}</span><span>{t.shortcut}</span></div>{commands.map(c=><button type="button" role="option" aria-selected={selected===c.id} id={`shortcut-${c.id}`} key={c.id} tabIndex={-1} className={selected===c.id?'selected':''} onClick={()=>choose(c.id)}><span><small>{c.category}</small>{c.label}</span><kbd>{displayKey(binding(draft!.settings,c))||'—'}</kbd></button>)}{draft&&!commands.length&&<p>{t.empty}</p>}</div>
 <fieldset className="shortcut-assignment" disabled={busy||!command}><strong>{command?.label??t.choose}</strong><label>{t.shortcut}<input aria-label={t.record} placeholder={t.record} readOnly value={displayKey(candidate)} onKeyDown={e=>{e.stopPropagation();if(e.key==='Tab')return;e.preventDefault();if(e.nativeEvent.isComposing||e.repeat||['Shift','Control','Alt','Meta','CapsLock'].includes(e.key))return;if(e.key==='Escape'){setCandidate('');return;}setCandidate(eventKey(e.nativeEvent));setError('');}}/></label><div className="shortcut-default">{t.default}: {displayKey(command?.defaultKey??'')||t.unassigned}</div><button type="button" disabled={!candidate||!!invalid||conflicts.length>0} onClick={()=>assign()}>{t.assign}</button><button type="button" onClick={()=>{if(command)setKey(command.id,'');setCandidate('');}}>{t.clear}</button><button type="button" onClick={()=>{if(command){if(command.defaultKey)setCandidate(command.defaultKey);else setKey(command.id,'');}}}>{t.reset}</button>
 {invalid&&<p role="alert">{t.invalid}</p>}{conflicts.length>0&&<div className="shortcut-conflict" role="alert"><p>{t.conflict}</p>{conflicts.map(c=><strong key={c.id}>{c.category} · {c.label}</strong>)}<button type="button" onClick={()=>{const id=conflicts[0].id;setArea('');setQuery('');choose(id);requestAnimationFrame(()=>document.getElementById(`shortcut-${id}`)?.scrollIntoView({block:'nearest'}));}}>{t.jump}</button><button type="button" onClick={()=>assign(true)}>{t.reassign}</button></div>}</fieldset></div>
 {error&&<p className="shortcut-error" role="alert">{error}</p>}<footer><button type="button" disabled={!draft||busy} onClick={()=>void exportText()}>{t.export}</button><span/><button type="button" disabled={busy} onClick={onClose}>{t.cancel}</button><button className="primary" type="submit" disabled={!draft||busy||!!candidate}>{busy?t.saving:t.ok}</button></footer>
 </form></dialog>;
}
