import { useEffect, useState } from 'react';
import { applyGradient, swatchLibrary, watchSwatches, type Brush, type DocumentSnapshot, type Gradient, type Swatch, type SwatchDraft } from '../bridge';
import { type Locale } from '../i18n';
import { ColorPickerPopover } from './ColorPickerPopover';
import { GradientPanel, gradientCss } from './GradientPanel';
import { swatchSeeds } from './swatchSeeds';
import { toHex } from './BrushControls';
import type { VectorColorControls } from './ColorPanel';
import './swatches-panel.css';
export const swatchLabels = {
  ja:{title:'スウォッチ',all:'すべて',color:'カラー',gradient:'グラデーション',search:'スウォッチを検索',grid:'サムネイル表示',list:'リスト表示',addColor:'カラーを追加',addGradient:'グラデーションを追加',current:'選択オブジェクトから追加',edit:'編集',duplicate:'複製',remove:'削除',name:'名前',save:'保存',cancel:'キャンセル',load:'読み込み',export:'書き出し',apply:'適用',fill:'塗り',stroke:'線',foreground:'描画色',background:'背景色',empty:'該当するスウォッチがありません。',preview:'編集内容は保存するまで反映されません。',newColor:'新しいカラー',newGradient:'新しいグラデーション',full:'登録できるスウォッチは512件までです。'},
  en:{title:'Swatches',all:'All',color:'Colors',gradient:'Gradients',search:'Search swatches',grid:'Thumbnail view',list:'List view',addColor:'Add color',addGradient:'Add gradient',current:'Add from selection',edit:'Edit',duplicate:'Duplicate',remove:'Delete',name:'Name',save:'Save',cancel:'Cancel',load:'Import',export:'Export',apply:'Apply',fill:'Fill',stroke:'Stroke',foreground:'Foreground',background:'Background',empty:'No matching swatches.',preview:'Edits take effect when saved.',newColor:'New color',newGradient:'New gradient',full:'Up to 512 swatches can be saved.'},
  'zh-CN':{title:'色板',all:'全部',color:'颜色',gradient:'渐变',search:'搜索色板',grid:'缩略图视图',list:'列表视图',addColor:'添加颜色',addGradient:'添加渐变',current:'从选中对象添加',edit:'编辑',duplicate:'复制',remove:'删除',name:'名称',save:'保存',cancel:'取消',load:'导入',export:'导出',apply:'应用',fill:'填色',stroke:'描边',foreground:'前景色',background:'背景色',empty:'没有匹配的色板。',preview:'编辑内容保存后生效。',newColor:'新颜色',newGradient:'新渐变',full:'最多可保存512个色板。'},
};
const initialGradient:Gradient={kind:'linear',angle:0,aspect:1,method:'classic',dither:false,stops:[{position:0,color:[255,255,255,255],midpoint:.5},{position:1,color:[0,0,0,255],midpoint:.5}]};
export function SwatchesPanel({locale,document,enabled,brush,backgroundColor,onForegroundChange,onBackgroundChange,vectorColors,onUpdate,initialDraft}:{initialDraft?:SwatchDraft;locale:Locale;document:DocumentSnapshot;enabled:boolean;brush:Brush;backgroundColor:Brush['color'];onForegroundChange:(c:Brush['color'])=>void;onBackgroundChange:(c:Brush['color'])=>void;vectorColors?:VectorColorControls;onUpdate:(d:DocumentSnapshot)=>void}){
  const t=swatchLabels[locale];const [items,setItems]=useState<Swatch[]>([]);const [selected,setSelected]=useState<number|null>(null);const [filter,setFilter]=useState<'all'|'color'|'gradient'>('all');const [search,setSearch]=useState('');const [list,setList]=useState(false);const [target,setTarget]=useState<'fill'|'stroke'>('fill');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [editor,setEditor]=useState<{id?:number;draft:SwatchDraft}|null>(()=>initialDraft?{draft:structuredClone(initialDraft)}:null);
  useEffect(()=>{let live=true;let unlisten:(()=>void)|undefined;const refresh=()=>swatchLibrary('get',undefined,undefined,swatchSeeds()).then(v=>{if(live)setItems(v);}).catch(e=>{if(live)setError(String(e));});void refresh();void watchSwatches(()=>{void refresh();}).then(fn=>{if(live)unlisten=fn;else fn();});return()=>{live=false;unlisten?.();};},[]);
  const chosen=items.find(s=>s.id===selected);
  const objects=document.layers.flatMap(l=>l.objects.filter(o=>document.selectedVectorObjects.includes(o.id)).map(o=>({l,o})));
  const vector=objects.length>0;
  const layer=document.layers.find(l=>l.id===document.layerId);
  const gradientEnabled=enabled&&!document.activeSavedPath&&(vector?objects.every(({l,o})=>l.kind==='vector'&&l.visible&&!l.locked&&o.visible&&!o.locked&&o.kind!=='text'):layer?.kind==='paint'&&layer.visible&&!layer.locked&&!layer.alphaLocked);
  const currentColor=vectorColors?(target==='fill'?vectorColors.fill:vectorColors.stroke):target==='fill'?brush.color:backgroundColor;
  const currentGradient=target==='fill'?objects[0]?.o.fillGradient:objects[0]?.o.strokeGradient;
  const appearanceMatches=(s:Swatch)=>s.paint.kind==='color'?!currentGradient&&toHex(s.paint.color)===toHex(currentColor):JSON.stringify(s.paint.gradient)===JSON.stringify(currentGradient);
  async function mutate(action:'add'|'update'|'remove'|'import'|'export',draft?:SwatchDraft,id?:number){setBusy(true);setError('');try{const next=await swatchLibrary(action,draft,id);setItems(next);if(action==='add')setSelected(next.at(-1)?.id??null);if(action==='remove')setSelected(null);if(action==='add'||action==='update')setEditor(null);}catch(e){setError(String(e));}finally{setBusy(false);}}
  async function apply(s:Swatch){setSelected(s.id);setError('');if(s.paint.kind==='color'){if(vectorColors){if(enabled)vectorColors.change(target,s.paint.color);}else if(target==='fill')onForegroundChange(s.paint.color);else onBackgroundChange(s.paint.color);return;}if(!gradientEnabled)return;setBusy(true);try{onUpdate(await applyGradient(document.selectedVectorObjects,vector?target:'pixels',vector&&target==='stroke'?{...s.paint.gradient,dither:false}:s.paint.gradient));}catch(e){setError(String(e));}finally{setBusy(false);}}
  const visible=items.filter(s=>(filter==='all'||s.paint.kind===filter)&&s.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  return <div className="swatches-panel"><header><h2>{t.title}</h2><span>{items.length}/512</span></header>
    <label className="swatches-target"><span>{vector?t.fill+' / '+t.stroke:t.foreground+' / '+t.background}</span><select value={target} onChange={e=>setTarget(e.target.value as 'fill'|'stroke')}><option value="fill">{vector?t.fill:t.foreground}</option><option value="stroke">{vector?t.stroke:t.background}</option></select></label>
    <div className="swatches-filters"><select aria-label={t.title} value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">{t.all}</option><option value="color">{t.color}</option><option value="gradient">{t.gradient}</option></select><button title={t.grid} aria-label={t.grid} aria-pressed={!list} onClick={()=>setList(false)}>▦</button><button title={t.list} aria-label={t.list} aria-pressed={list} onClick={()=>setList(true)}>☷</button></div>
    <input className="swatches-search" aria-label={t.search} placeholder={t.search} value={search} onChange={e=>setSearch(e.target.value)}/>
    <div className={`swatches-items ${list?'list':'grid'}`} role="group" aria-label={t.title}>{visible.map(s=><button key={s.id} disabled={busy} title={`${s.name} · ${s.paint.kind==='color'?t.color:t.gradient}`} aria-label={s.name} aria-pressed={s.id===selected} className={appearanceMatches(s)?'applied':''} onClick={()=>void apply(s)} onDoubleClick={()=>setEditor({id:s.id,draft:structuredClone(s)})}><span className="swatches-chip" style={{background:s.paint.kind==='color'?toHex(s.paint.color):gradientCss(s.paint.gradient)}}/>{list&&<span>{s.name}</span>}</button>)}</div>{!visible.length&&<p>{t.empty}</p>}
    <fieldset disabled={busy||items.length>=512} className="swatches-actions"><button onClick={()=>setEditor({draft:{name:t.newColor,paint:{kind:'color',color:currentColor}}})}>{t.addColor}</button><button onClick={()=>setEditor({draft:{name:t.newGradient,paint:{kind:'gradient',gradient:structuredClone(currentGradient??initialGradient)}}})}>{t.addGradient}</button><button disabled={!vector} onClick={()=>setEditor({draft:{name:currentGradient?t.newGradient:toHex(currentColor).toUpperCase(),paint:currentGradient?{kind:'gradient',gradient:structuredClone(currentGradient)}:{kind:'color',color:currentColor}}})}>{t.current}</button></fieldset>
    <fieldset disabled={busy} className="swatches-actions"><button disabled={!chosen} onClick={()=>chosen&&setEditor({id:chosen.id,draft:structuredClone(chosen)})}>{t.edit}</button><button disabled={!chosen||items.length>=512} onClick={()=>chosen&&setEditor({draft:{name:Array.from(chosen.name).slice(0,78).join('')+' 2',paint:structuredClone(chosen.paint)}})}>{t.duplicate}</button><button disabled={!chosen} onClick={()=>chosen&&void mutate('remove',undefined,chosen.id)}>{t.remove}</button><button disabled={!chosen||(chosen.paint.kind==='gradient'&&!gradientEnabled)} onClick={()=>chosen&&void apply(chosen)}>{t.apply}</button><button onClick={()=>void mutate('import')}>{t.load}</button><button disabled={!items.length} onClick={()=>void mutate('export')}>{t.export}</button></fieldset>
    {editor&&<section className="swatch-editor" aria-label={t.edit}><h3>{t.edit}</h3><label className="swatches-target"><span>{t.name}</span><input disabled={busy} maxLength={80} value={editor.draft.name} onChange={e=>setEditor({...editor,draft:{...editor.draft,name:e.target.value}})}/></label>
    {editor.draft.paint.kind==='color'?<ColorPickerPopover locale={locale} label={t.color} color={editor.draft.paint.color} disabled={busy} onChange={color=>setEditor(v=>v?{...v,draft:{...v.draft,paint:{kind:'color',color}}}:v)}/>:<GradientPanel key={editor.id??'new'} locale={locale} document={document} enabled={!busy} onUpdate={onUpdate} editorGradient={editor.draft.paint.gradient} onDraft={gradient=>setEditor(v=>v?{...v,draft:{...v.draft,paint:{kind:'gradient',gradient}}}:v)}/>}
    <p>{t.preview}</p><div className="swatches-actions"><button disabled={busy||!editor.draft.name.trim()} onClick={()=>void mutate(editor.id===undefined?'add':'update',{name:editor.draft.name.trim(),paint:editor.draft.paint},editor.id)}>{t.save}</button><button disabled={busy} onClick={()=>setEditor(null)}>{t.cancel}</button></div></section>}
    {error&&<p className="swatches-error" role="alert">{error}</p>}
  </div>;
}
