import type { Locale } from './i18n';
export const toneKinds = ['dot','gradient','line','pattern','cg','sand','crosshatch','effect','background','white','transfer','color','copy'] as const;
export type ToneKind = typeof toneKinds[number];
export interface Screentone {
  kind: ToneKind; variant: number; frequency: number; dpi: number; density: number; size: number;
  angle: number; offset: [number,number]; gradientEnd: number; extent: number; seed: number;
  color: [number,number,number]; paper: boolean; luminance: boolean; inverted: boolean;
}
export const defaultScreentone = (dpi = 300): Screentone => ({kind:'dot',variant:0,frequency:Math.max(1,Math.min(60,Math.round(dpi/6))),dpi,density:30,size:1,angle:45,offset:[0,0],gradientEnd:0,extent:600,seed:1,color:[0,0,0],paper:false,luminance:false,inverted:false});
export const screentoneLabels = {
  ja:{title:'スクリーントーン',kind:'分類',design:'デザイン',frequency:'線数 (lpi)',density:'濃度 (%)',size:'点・線のサイズ',angle:'角度 (°)',x:'柄の位置 X (px)',y:'柄の位置 Y (px)',end:'終了濃度 (%)',extent:'変化の距離 (px)',seed:'乱数シード',color:'インク色',paper:'余白を白で塗る',luminance:'元画像の明暗を反映',inverted:'濃度を反転',apply:'選択レイヤーに適用',create:'新規トーンレイヤー',remove:'トーンを解除',hint:'新規作成は選択範囲に貼り付けます。選択範囲がない場合は原稿全体に作成します。',existing:'適用先の描画部分をトーン化します。数値を変更後、適用を押してください。',white:'ホワイトトーンは暗い下地で確認してください。',copy:'コピートーンは元画像の明暗を網点に変換します。',transfer:'転写トーンは、かすれた転写の質感を生成します。',resolution:'原稿の解像度',families:['アミトーン（網点）','グラデーショントーン','万線トーン','柄トーン','CGトーン','砂目トーン','カケアミトーン','効果トーン','背景トーン','ホワイトトーン','転写トーン','カラートーン','コピートーン']},
  en:{title:'Screentones',kind:'Category',design:'Design',frequency:'Frequency (lpi)',density:'Density (%)',size:'Dot / line size',angle:'Angle (°)',x:'Pattern X (px)',y:'Pattern Y (px)',end:'End density (%)',extent:'Gradient length (px)',seed:'Random seed',color:'Ink color',paper:'Fill gaps with white',luminance:'Use source luminance',inverted:'Invert density',apply:'Apply to selected layer',create:'New tone layer',remove:'Remove tone',hint:'New layers fill the selection, or the entire canvas when there is no selection.',existing:'Apply converts the painted area of the selected layer. Press Apply after editing settings.',white:'View white tones over a dark background.',copy:'Copy tones convert source luminance into halftone dots.',transfer:'Transfer tones generate a distressed transfer texture.',resolution:'Document resolution',families:['Dot','Gradient','Parallel lines','Pattern','CG','Sand','Crosshatch','Effect','Background','White','Transfer','Color','Copy']},
  'zh-CN':{title:'网点纸',kind:'分类',design:'设计',frequency:'线数 (lpi)',density:'浓度 (%)',size:'点 / 线尺寸',angle:'角度 (°)',x:'图案位置 X (px)',y:'图案位置 Y (px)',end:'结束浓度 (%)',extent:'渐变距离 (px)',seed:'随机种子',color:'墨色',paper:'用白色填充空隙',luminance:'使用原图明暗',inverted:'反转浓度',apply:'应用到所选图层',create:'新建网点图层',remove:'移除网点',hint:'新图层填充选区。没有选区时填充整个画布。',existing:'将所选图层的绘制区域转换为网点。修改设置后点击应用。',white:'请在深色背景上查看白色网点。',copy:'复印网点将原图明暗转换为网点。',transfer:'转印网点生成斑驳的转印质感。',resolution:'画布分辨率',families:['网点','渐变网点','平行线','图案','CG','砂目','交叉排线','效果','背景','白色','转印','彩色','复印']},
};
const designs = {
  ja:[['円','四角','菱形','楕円'],['線形','円形','反射','波形'],['直線','波線','破線','二重線'],['格子','菱形格子','花','市松'],['ウェーブ','干渉','同心波','雲状'],['粗い砂','中粒','細粒','微粒'],['交差','三方向','手描き風','編み目'],['集中線','スピード線','同心円','放射フラッシュ'],['雨','レンガ','雲','木目'],['丸抜き','角抜き','菱形抜き','楕円抜き'],['かすれ網点','粒状','かすれ線','布目'],['丸ドット','角ドット','菱形ドット','楕円ドット'],['丸網点','角網点','菱形網点','楕円網点']],
  en:[['Circle','Square','Diamond','Ellipse'],['Linear','Radial','Reflected','Wave'],['Straight','Wavy','Dashed','Double'],['Grid','Diamond grid','Flowers','Checker'],['Wave','Interference','Ripples','Cloud'],['Coarse','Medium','Fine','Micro'],['Cross','Three directions','Sketch','Weave'],['Focus lines','Speed lines','Rings','Radial flash'],['Rain','Bricks','Clouds','Wood grain'],['Circle','Square','Diamond','Ellipse'],['Distressed dots','Grain','Distressed lines','Fabric'],['Round dots','Square dots','Diamond dots','Elliptical dots'],['Round screen','Square screen','Diamond screen','Elliptical screen']],
  'zh-CN':[['圆形','方形','菱形','椭圆'],['线性','径向','反射','波形'],['直线','波线','虚线','双线'],['格子','菱格','花朵','棋盘'],['波浪','干涉','同心波','云纹'],['粗砂','中粒','细粒','微粒'],['交叉','三方向','手绘','编织'],['集中线','速度线','同心圆','放射闪光'],['雨','砖墙','云','木纹'],['圆形','方形','菱形','椭圆'],['斑驳网点','颗粒','斑驳线','布纹'],['圆点','方点','菱形点','椭圆点'],['圆网点','方网点','菱形网点','椭圆网点']],
};
export const toneDesigns = (locale:Locale,kind:ToneKind) => designs[locale][toneKinds.indexOf(kind)];
